# Cấu hình kết nối MariaDB
db.url=jdbc:mariadb://localhost:3306/StarGuardianDB?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Ho_Chi_Minh
db.user=root
db.password=sapassword


socket.host=localhost
socket.port=9841
